language: go

go:
  - 1.13.x

env:
  global:
    - MYAPP=serval
    - MYEMAIL=sumin.200ok@gmail.com

before_install:
  - sudo apt-get -qq update

install:
  - go get -u github.com/bardex/$MYAPP
  - cd $GOPATH/src/github.com/bardex/$MYAPP
  - go install


before_deploy:
  - mkdir -p build/
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER} -X main.commit=${TRAVIS_COMMIT}" -o build/${MYAPP}-amd64-linux *.go
  - GOOS=windows GOARCH=amd64 go build --ldflags "-X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER} -X main.commit=${TRAVIS_COMMIT}" -o build/${MYAPP}-amd64-win.exe *.go
  - GOOS=darwin GOARCH=amd64 go build --ldflags "-X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER} -X main.commit=${TRAVIS_COMMIT}" -o build/${MYAPP}-amd64-macos *.go

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - build/${MYAPP}-amd64-linux
    - build/${MYAPP}-amd64-win.exe
    - build/${MYAPP}-amd64-macos
  skip_cleanup: true
  on:
    tags: true
    all_branches: true