language: go

go:
  - 1.13.x

git:
  depth: 3

env:
  global:
    - MYAPP=serval
    - MYEMAIL=sumin.200ok@gmail.com
    - GO111MODULE=on

before_install:
  - sudo apt-get -qq update

install:
  - pwd
  - ls -l
  - go get -u github.com/gobuffalo/packr/v2/packr2
  - packr2 clean
  - packr2

before_deploy:
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.ReleaseMode=release -X main.Version=${TRAVIS_TAG} -X main.Build=${TRAVIS_BUILD_NUMBER}" -o ${MYAPP}_${TRAVIS_TAG}_amd64_linux *.go
  - GOOS=windows GOARCH=amd64 go build --ldflags "-X main.ReleaseMode=release -X main.Version=${TRAVIS_TAG} -X main.Build=${TRAVIS_BUILD_NUMBER}" -o ${MYAPP}_${TRAVIS_TAG}_amd64_win.exe *.go

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - ${MYAPP}_${TRAVIS_TAG}_amd64_linux
    - ${MYAPP}_${TRAVIS_TAG}_amd64_win.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true