language: go

go:
  - 1.13.x

env:
  global:
    - MYAPP=serval
    - MYEMAIL=sumin.200ok@gmail.com
    - GIN_MODE=release

before_install:
  - sudo apt-get -qq update

install:
  - go get -u github.com/bardex/$MYAPP
  - cd $GOPATH/src/github.com/bardex/$MYAPP
  - go build -o test_build
  - ls -l

before_deploy:
  - mkdir -p build/
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X ReleaseMode=release -X main.version=${TRAVIS_TAG} -X main.build=${TRAVIS_BUILD_NUMBER}" -o build/${MYAPP}_${TRAVIS_TAG}_amd64_linux *.go

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - build/${MYAPP}_${TRAVIS_TAG}_amd64_linux
  skip_cleanup: true
  on:
    tags: true
    all_branches: true