language: go

go:
  - 1.13.x

env:
  global:
    - MYAPP=serval
    - MYEMAIL=sumin.200ok@gmail.com
    - GO111MODULE=on

before_install:
  - sudo apt-get -qq update

install:
  - pwd
  - ls -l
  - GO111MODULE=on go get -u github.com/bardex/$MYAPP
  - cd $GOPATH/src/github.com/bardex/$MYAPP
  - go get -u github.com/gobuffalo/packr/v2/packr2
  - packr2 clean
  - packr2
  - go test -v ./...

before_deploy:
  - mkdir -p build/
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.ReleaseMode=release -X main.Version=${TRAVIS_TAG} -X main.Build=${TRAVIS_BUILD_NUMBER}" -o build/${MYAPP}_${TRAVIS_TAG}_amd64_linux *.go
  - GOOS=windows GOARCH=amd64 go build --ldflags "-X main.ReleaseMode=release -X main.Version=${TRAVIS_TAG} -X main.Build=${TRAVIS_BUILD_NUMBER}" -o build/${MYAPP}_${TRAVIS_TAG}_amd64_win.exe *.go

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - build/${MYAPP}_${TRAVIS_TAG}_amd64_linux
    - build/${MYAPP}_${TRAVIS_TAG}_amd64_win.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true