// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "15bd2693b5797fc17f07b2c780649f5e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b720a873e63cfa65bb6a30564fc5b4ba": "1f8b08000000000000ff5c53bd6edc300cdefd148c960eadad642b0ac945871608902e4ddb9d27f1ce4c64c99078e75c9ebeb07db9b89e6849fcf8fd1036373e39390f049df4a1adcc5420603c5845514d1784bead00004c4f82e03acc85c4aa3fbf7fd49fd5e529707c862ed3deaa4e64285fb4dea728a539a47408840397c6a55eb34bf1eb1e7b0e67fb13853263f878ef522c0a3205ab8a9c03958e48de46dfd4f57d3fa42cd05f00fc4a8d2ba5aed7e45bf4468df3f1a9342ea4a3df07cc34abc1277cd1817745af46ebbbe6b6b9d5aefc77dbf41c2752d55657590f24b0cb692c94e139a61146da1516022e9006e19e5fc9c33e65e8d38e035d05cf4146ecc9aa13d3389953e052148a62d5c85e3aebe9c48eeaf9f00938b23086ba380c64ef9a5ba5df84084ba0f691f20903d410d2e14381722e42bdd1cb635519bdecb132bbe4cf53f57c02f656e1305c3d453c2d0ae7d3d4e102966255c4533d661c06cab34ee44859bdf7cefd78895cab37d82e63f47548870481f6a2dac7efbffe7e7b301a37d06398b54c344b54d711990f9d6c982e4b6f4d4e47a15ccffb976495e6e8e9858a6aef970fa3572dadd18137c4fa18568eb5e74b0046cf5954db20d6e6ab15a67aaf4bc0462f3fd4bf000000ffffb83761ec61030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "assets/templates")
		b.SetResolver("home.html", packr.Pointer{ForwardBox: gk, ForwardPath: "b720a873e63cfa65bb6a30564fc5b4ba"})
	}()
	return nil
}()
