// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "15bd2693b5797fc17f07b2c780649f5e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b720a873e63cfa65bb6a30564fc5b4ba": "1f8b08000000000000ff5c93416fdb3c0c86effe15aaaedf67abbd0d83e461870d28d05dd66d77466262b6b464484cdcf4d70fb693d4f389a644f27df45ab2772179390fa83ae9b9adec1414433c388d514f0b08a1ad9452caf628a07c07b9a038fdfbd7f7fa93be6c31c557d565dc3bdd890ce5b331fb14a53487940e8c3050697cea0df914bfeca1273ebb1f209809f8bf479f62d12a233b5de4cc583a44b98ebeabebc77e4859547f69a0776c7c2975bd16df766f687c882fa5f19c8e61cf9071a6811778334cbb6256a3cd4373dfdc1b5ffe596d7a8a93a86eab1bd6138adae53416ccea35a6518db82b24a8a8a83408f5f48e41ed53567dda11e30d783632428f4e9f08c7e9705af91405a3383d5290ce053c91c77a4efe57144908b82e1e18dd4373afcd15444818db67cc27606b96acaaac597e5c6577299ca718e8a428380dc3703b4484d382346753856728c5e908a77acc300c986730a088597fd4cef570f1d8e86bdb2e430c35a743528c7bd1edf3b79f7fbe3ed9721c5a5b7a606e81870eac59126be61d039bc9479e51278ac5ba9b42a643271b90cb25686d4e47c15ccff74192d38662c0372cba7d5c3eac5995b4d6306d84cd9157869840177fac99adaab63eadbda9563dd5475cfcb76679607f030000ffff2cfb1f9c71030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "assets/templates")
		b.SetResolver("home.html", packr.Pointer{ForwardBox: gk, ForwardPath: "b720a873e63cfa65bb6a30564fc5b4ba"})
	}()
	return nil
}()
